version: 2.1
orbs:
  node: circleci/node@1.1
  
jobs:
  FE_CI:
    executor:
      name: node/default
      tag: '12.16.1'
    working_directory: ~/project/FE
    steps:
      - checkout:
          path: ~/project
      - run: echo "$(pwd)"
      - run: echo "$(ls -la)"
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
      - run: CI='' npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./build
  Hello:
    executor:
      name: node/default
      tag: '12.16.1' 
    working_directory: ~/project/BE
    steps:
      - run: echo "Hello World"
  
  Deploy:
    executor:
      name: node/default
      tag: '12.16.1' 
    working_directory: ~/project/FE
    steps:
      - attach_workspace:
          at: .
      - run: echo "$(pwd)"
      - run: echo "$(ls -la)"
      - run: sudo apt install awscli
      - run: sudo aws configure set region $REGION
      - run: sudo aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - run: sudo aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run: sudo aws s3 cp ./build s3://$BUCKET_NAME/ --acl=bucket-owner-full-control

        
workflows:
  version: 2
  build_and_test: 
    jobs: 
      - FE_CI
      - Hello
      - Deploy:
          requires:
            - FE_CI
         
