version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - run: echo "$(pwd)"
      - run: echo "$(ls -la)"
      - node/with-cache:
          steps:
            - run: cd FE && npm install
      - run: cd FE && npm run test