version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    working_directory: ~/project/FE
    steps:
      - checkout:
          path: ~/project
      - run: echo "$(pwd)"
      - run: echo "$(ls -la)"
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test